# -*- coding: utf-8 -*-
"""Image Processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEEqxNittH8LSpmoNvt5pT_lelEbX2Vb
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("3ab9c933-83ed-4bc2-ab21-7f52cf5e5fbc.jpg")

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
eq = cv2.equalizeHist(gray)
h, w = gray.shape
resized = cv2.resize(gray, (int(w*1.5), int(h*1.5)))

hist_gray = cv2.calcHist([gray], [0], None, [256], [0, 256])
hist_eq   = cv2.calcHist([eq],   [0], None, [256], [0, 256])

fig, axes = plt.subplots(2, 4, figsize=(20, 8))
axes[0,0].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB)); axes[0,0].set_title("Original");        axes[0,0].axis("off")
axes[0,1].imshow(gray,    cmap="gray");                  axes[0,1].set_title("Grayscale");       axes[0,1].axis("off")
axes[0,2].imshow(resized, cmap="gray");                  axes[0,2].set_title("Resized 150%");    axes[0,2].axis("off")
axes[0,3].imshow(eq,      cmap="gray");                  axes[0,3].set_title("Equalized");       axes[0,3].axis("off")
axes[1,0].imshow(np.hstack([gray, eq]), cmap="gray");    axes[1,0].set_title("Gray | Equalized");axes[1,0].axis("off")
axes[1,1].plot(hist_gray.ravel()); axes[1,1].set_title("Hist - Gray");     axes[1,1].set_xlim([0,256])
axes[1,2].plot(hist_eq.ravel());   axes[1,2].set_title("Hist - Equalized");axes[1,2].set_xlim([0,256])
axes[1,3].axis("off")
plt.tight_layout(); plt.savefig("B1_results.png", dpi=150); plt.show()

for label, im in [("Original", img), ("Grayscale", gray)]:
    src = im
    print(f"\n{label}: size={src.shape[:2]}, channels={1 if src.ndim==2 else src.shape[2]}, dtype={src.dtype}, min={src.min()}, max={src.max()}")